.PHONY: clean reset

beamer: $(FILE)
beamer: TEMPLATE ?= etc/pandoc-beamer.tex
beamer: THEME ?= ulille
beamer: SLIDELEVEL ?= 2
beamer: ARGS += -t beamer
beamer: ARGS += --slide-level=$(SLIDELEVEL)

report: $(FILE)
report: TEMPLATE ?= etc/pandoc-report.tex
report: THEME ?= cgir
report: ARGS += -t latex
report: ARGS += --top-level-division=chapter
report: ARGS += -N

ARGS = --standalone
ARGS += --template=$(TEMPLATE)
ARGS += -L etc/include-files.lua
ARGS += -L etc/include-code-files.lua
ARGS += -L etc/center-image.lua
ARGS += -L etc/svg-image-to-pdf.lua
ARGS += -V theme=$(THEME)
ARGS += --pdf-engine-opt=-shell-escape
ARGS += --toc
ARGS += --highlight-style=tango

%.pdf: %.md makefile $(wildcard etc/*)
	TEXINPUTS=.//: pandoc $(ARGS) $(EXTRAS) -o $@ $< 

clean:
	-rm *~

reset: clean
